name: Microsoft Defender For DevOps Scan

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  defender-for-devops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Microsoft Security DevOps
        id: msdo
        uses: microsoft/security-devops-action@v1

      - name: Upload results to Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
